{{- if eq .Values.blueGreen.enabled false }}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: {{ include "app.fullname" . }}
---
{{- end }}