{{- if .Values.blueGreen.enabled }}
{{- if .Values.blueGreen.blue.tag }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}-{{ .Values.blueGreen.blue.name }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}-{{ .Values.blueGreen.blue.name }}
---
{{- end }}
{{- if .Values.blueGreen.green.tag }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}-{{ .Values.blueGreen.green.name }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}-{{ .Values.blueGreen.green.name }}
---
{{- end }}
{{- end }}